language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t kartiktewari9/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kartiktewari9/docker-react npm run test
